### ISSUE TITLE
Make a Casdoor operator inside Kubernetes (k8s)

### ISSUE THREAD

**Issue by hsluoyz** [casdoor/casdoor-operator#1]
A Casdoor operator that help run Casdoor clusters inside k8s, like: https://github.com/zalando/postgres-operator

**Comment by hsluoyz** [comment]
@Abingcbc

**Comment by Abingcbc** [comment]
# Proposal
## Feature
1. Auto create `deployment` and `service` for Casdoor
2. Auto merge configurations. Users only need to specify configurations that they want to override the default one.
3. Auto reload Casdoor if the configuration is changed
4. Auto fill init data template to init Casdoor 
5. Auto create local static file server if enabled

## Custom Resource Definition
```go
// CasdoorSpec defines the desired state of Casdoor
type CasdoorSpec struct {
	// items for `app.conf`
	AppConf map[string]string `json:"appConf,omitempty"`

	// items for `init_data.json`
	// key is jsonpath of the item like `organization[0].name`
	InitData map[string]string `json:"initData,omitempty"`

	// in-cluster static file server
	InClusterCDN bool `json:"inClusterCDN,omitempty"`
}

// CasdoorStatus defines the observed state of Casdoor
type CasdoorStatus struct {
	// active Casdoor instances
	Active []corev1.ObjectReference `json:"active,omitempty"`

	// reason if failed
	Reason string `json:"reason,omitempty"`
}
```

**Comment by hsluoyz** [comment]
@Abingcbc the plan looks good! When can we have a PR?

**Comment by fanux** [comment]
It's awesome, [sealos](https://github.com/labring/sealos) need this operator.
